#!/bin/bash

rm -rf dist && \
  npm run build:demo && \
  cp -r demo/{index.html,demo.css} dist && \
  cd dist && \
  git init && \
  git remote add origin git@github.com:meriadec/overdraft.git && \
  git add . && \
  git commit -m 'deploy' && \
  git push -f origin master:gh-pages && \
  printf '\n> everything has been deployed\n'
